[package]
name = "blkrs"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A CLI tool to read and write blocks of data from a file or device with logging and exception handling capabilities."
documentation = "docs.rs/blkrs"
repository = "https://github.com/rstrategist/rust-cli-utils"

[dependencies]
clap = { version = "4.2", features = ["derive", "env"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.10"
